name: aws-v5
on:
  push:
    branches:
      - main

# https://github.com/actions/setup-java
# actions/setup-java@v2는 사용자 정의 배포를 지원하고 Zulu OpenJDK, Eclipse Temurin 및 Adopt OpenJDK를 기본적으로 지원합니다. v1은 Zulu OpenJDK만 지원합니다.
jobs:
  build: # 마음대로 적어도 됨
    runs-on: ubuntu-latest
    steps:
      #4개의 스탭
      - name: Checkout # 안 적어도 됨
        uses: actions/checkout@v3 # 코드 다운로드 스크립트 실행
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: zulu
      - name: Pemission
        run: chmod +x ./gradlew # 메이븐 사용하면 명령어 달라지니 미리 정해진 action 없음
      - name: Build with Gradle
        run: ./gradlew clean build # 깔끔하게 빌드폴더 통채로 날리고 다시 빌드
